# Generated by Django 4.2.4 on 2023-11-22 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos_canje', '0001_initial'),
        ('users', '0004_delete_administrador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('puntos_restados', models.IntegerField()),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.cliente')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos_canje.productocanje')),
            ],
        ),
    ]
