# Generated by Django 4.2.4 on 2023-11-22 20:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canjes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canje',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
