export * from "./Home";
export * from "./EntradasCliente";
export * from "./FuncionesPelicula";
export * from "./CompraEntradas"
export * from "./LoginRegister"
export * from "./Perfil"
export * from "./Canjes"
export * from "./Mapa.js"
export * from "./ProductosCanje"
export * from "./Verificacion";