# Generated by Django 4.2.4 on 2023-09-25 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('establecimientos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('precio_entrada', models.IntegerField()),
                ('idEstablecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establecimientos.establecimiento')),
            ],
        ),
    ]
