# Generated by Django 4.2.4 on 2023-11-27 02:16

from django.db import migrations, models
import peliculas.models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0002_alter_pelicula_descripcion_corta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='poster',
            field=models.ImageField(blank=True, upload_to=peliculas.models.get_file_path),
        ),
    ]
