# Generated by Django 4.2.4 on 2023-11-27 02:16

from django.db import migrations, models
import productos_canje.models


class Migration(migrations.Migration):

    dependencies = [
        ('productos_canje', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productocanje',
            name='imagen',
            field=models.ImageField(blank=True, upload_to=productos_canje.models.get_file_path),
        ),
    ]
